apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app.kubernetes.io/names: nodejs
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/component: http-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: nodejs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nodejs
    spec:
      containers:
        - name: nodejs-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
